### ISSUE TITLE
Cannot find the module 'express'

### ISSUE THREAD

**Issue by aswertyn** [Deezloader/DeezLoader-Reborn#2]
Hi, i dont know if i did some wrong with the install method but this is my problem. Eery time i want to launch it after the install and the first launch it doesn't work anymore. It shows me this: cannot find the module 'express' and more things. I can fix this erasing the folder and installing it again.
Sorry for my bad english. i'm mexican and i don't have good control with the language.

**Comment by mvxs** [comment]
Why would you install it at all? Use the portable version.
